In [ ]:
import pandas as pd

In [ ]:
customer = pd.read_csv('/content/olist_customers_dataset.csv')
customer.columns

Index(['customer_id', 'customer_unique_id', 'customer_zip_code_prefix',
       'customer_city', 'customer_state'],
      dtype='object')

In [ ]:
# delete columns 'customer_unique_id'
customers = customer.drop(['customer_unique_id'], axis=1)
customers.columns

Index(['customer_id', 'customer_zip_code_prefix', 'customer_city',
       'customer_state'],
      dtype='object')

In [ ]:
customer[['customer_city', 'customer_state']].isnull().sum()

customer_city     0
customer_state    0
dtype: int64

In [ ]:
customer.shape

(99441, 5)

In [ ]:
customer_id = customer['customer_id']
customer_id.to_csv('customer_id.csv', index=False)

In [ ]:
customer_id.shape

(99441,)

In [ ]:
customers.head(1)

,customer_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,14409,franca,SP

In [ ]:
# customer_id, customer_city, customer_state, customer_zip_code_prefix
# change the order of columns
customers = customers[['customer_id', 'customer_city', 'customer_state', 'customer_zip_code_prefix']]
customers.columns

Index(['customer_id', 'customer_city', 'customer_state',
       'customer_zip_code_prefix'],
      dtype='object')

In [ ]:
# export customer as a csv file
customers.to_csv('customers.csv', index=False)

In [ ]:
payments = pd.read_csv('/content/olist_order_payments_dataset.csv')
payments.columns

Index(['order_id', 'payment_sequential', 'payment_type',
       'payment_installments', 'payment_value'],
      dtype='object')

In [ ]:
payments[['payment_sequential', 'payment_type', 'payment_installments', 'payment_value']].isnull().sum()

payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

In [ ]:
payments.shape

(99440, 5)

In [ ]:
len(payments['order_id'].unique())

99440

In [ ]:
payments.drop_duplicates(subset='order_id', inplace=True)

In [ ]:
payments.shape

(99440, 5)

In [ ]:
payments.columns

Index(['order_id', 'payment_sequential', 'payment_type',
       'payment_installments', 'payment_value'],
      dtype='object')

In [ ]:
# payment_sequential, payment_type, payment_installments, payment_value, order_id
payments = payments[['payment_sequential', 'payment_type', 'payment_installments', 'payment_value', 'order_id']]
payments.columns

Index(['payment_sequential', 'payment_type', 'payment_installments',
       'payment_value', 'order_id'],
      dtype='object')

In [ ]:
payments.to_csv('payments.csv', index=False)

In [ ]:
reviews = pd.read_csv('/content/olist_order_reviews_dataset.csv')
reviews.columns

Index(['review_id', 'order_id', 'review_score', 'review_comment_title',
       'review_comment_message', 'review_creation_date',
       'review_answer_timestamp'],
      dtype='object')

In [ ]:
# delete order_id, review_answer_timestamp from reviews
reviews = reviews.drop(['order_id', 'review_answer_timestamp'], axis=1)
reviews.columns

Index(['review_id', 'review_score', 'review_comment_title',
       'review_comment_message', 'review_creation_date'],
      dtype='object')

In [ ]:
reviews[['review_score']].isnull().sum()

review_score    0
dtype: int64

In [ ]:
reviews.shape

(99224, 5)

In [ ]:
len(reviews['review_id'].unique())

98410

In [ ]:
reviews.drop_duplicates(subset='review_id', inplace=True)

In [ ]:
reviews.shape

(98410, 5)

In [ ]:
reviews.to_csv('reviews.csv', index=False)

In [ ]:
orders = pd.read_csv('/content/olist_orders_dataset.csv')
orders.columns

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date'],
      dtype='object')

In [ ]:
orders = orders.drop(['customer_id'], axis=1)
orders.columns

Index(['order_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date'],
      dtype='object')

In [ ]:
orders.shape

(99441, 7)

In [ ]:
orders[['order_status', 'order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date']].isnull().sum()

order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [ ]:
orders['customer_id'] = customer_id
orders.columns

Index(['order_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date',
       'customer_id'],
      dtype='object')

In [ ]:
orders.to_csv('orders.csv', index=False)

In [ ]:
reviews = pd.read_csv('/content/olist_order_reviews_dataset.csv')
reviews.columns

Index(['review_id', 'order_id', 'review_score', 'review_comment_title',
       'review_comment_message', 'review_creation_date',
       'review_answer_timestamp'],
      dtype='object')

In [ ]:
# review_id, review_score, review_comment_title, review_creation_date, order_id
reviews = reviews[['review_id', 'review_score', 'review_comment_title', 'review_creation_date', 'order_id']]
reviews.columns

Index(['review_id', 'review_score', 'review_comment_title',
       'review_creation_date', 'order_id'],
      dtype='object')

In [ ]:
reviews.shape

(99224, 5)

In [ ]:
reviews.drop_duplicates(subset='review_id', inplace=True)

In [ ]:
reviews.shape

(98410, 5)

In [ ]:
reviews.to_csv('reviews.csv', index=False)

In [ ]:
order_items = pd.read_csv('/content/olist_order_items_dataset.csv')
order_items.columns

Index(['order_id', 'order_item_id', 'product_id', 'seller_id',
       'shipping_limit_date', 'price', 'freight_value'],
      dtype='object')

In [ ]:
order_items.head(1)

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.9,13.29

In [ ]:
order_items.rename(columns={'order_item_id': 'items_quantity'}, inplace=True)
order_items.columns

Index(['order_id', 'items_quantity', 'product_id', 'seller_id',
       'shipping_limit_date', 'price', 'freight_value'],
      dtype='object')

In [ ]:
# items_quantity, shipping_limit_date, price, freight_value, order_detail_id, order_id, product_id, seller_id
order_items = order_items[['items_quantity', 'shipping_limit_date', 'price', 'freight_value', 'order_id', 'product_id', 'seller_id']]
order_items.columns

Index(['items_quantity', 'shipping_limit_date', 'price', 'freight_value',
       'order_id', 'product_id', 'seller_id'],
      dtype='object')

In [ ]:
order_items.to_csv('order_items.csv', index=False)

In [ ]:
products = pd.read_csv('/content/olist_products_dataset.csv')
products.columns

Index(['product_id', 'product_category_name', 'product_name_lenght',
       'product_description_lenght', 'product_photos_qty', 'product_weight_g',
       'product_length_cm', 'product_height_cm', 'product_width_cm'],
      dtype='object')

In [ ]:
products = products[['product_id', 'product_category_name', 'product_name_lenght', 'product_weight_g', 'product_length_cm', 'product_height_cm', 'product_width_cm']]
products.columns

Index(['product_id', 'product_category_name', 'product_name_lenght',
       'product_weight_g', 'product_length_cm', 'product_height_cm',
       'product_width_cm'],
      dtype='object')

In [ ]:
products.head()

,product_id,product_category_name,product_name_lenght,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,625.0,20.0,17.0,13.0

In [ ]:
products.dtypes

product_id                object
product_category_name     object
product_name_lenght      float64
product_weight_g         float64
product_length_cm        float64
product_height_cm        float64
product_width_cm         float64
dtype: object

In [ ]:
products.isnull().sum()

product_id                 0
product_category_name    610
product_name_lenght      610
product_weight_g           2
product_length_cm          2
product_height_cm          2
product_width_cm           2
dtype: int64

In [ ]:
products.fillna(0, inplace=True)
products.isnull().sum()

/tmp/ipykernel_748/1277723464.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  products.fillna(0, inplace=True)

product_id               0
product_category_name    0
product_name_lenght      0
product_weight_g         0
product_length_cm        0
product_height_cm        0
product_width_cm         0
dtype: int64

In [ ]:
# change the columns with dtype float to int
float_cols  = ['product_name_lenght', 'product_weight_g', 'product_length_cm', 'product_height_cm', 'product_width_cm']
products[float_cols] = products[float_cols].astype('int64')
products.dtypes

/tmp/ipykernel_748/1360356411.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  products[float_cols] = products[float_cols].astype('int64')

product_id               object
product_category_name    object
product_name_lenght       int64
product_weight_g          int64
product_length_cm         int64
product_height_cm         int64
product_width_cm          int64
dtype: object

In [ ]:
products.to_csv('products.csv', index=False)

In [ ]:
sellers = pd.read_csv('/content/olist_sellers_dataset.csv')
sellers.columns

Index(['seller_id', 'seller_zip_code_prefix', 'seller_city', 'seller_state'], dtype='object')

In [ ]:
sellers = sellers[['seller_id', 'seller_city', 'seller_state', 'seller_zip_code_prefix']]
sellers.columns

Index(['seller_id', 'seller_city', 'seller_state', 'seller_zip_code_prefix'], dtype='object')

In [ ]:
sellers.to_csv('sellers.csv', index=False)

In [ ]:
geolocation = pd.read_csv('/content/olist_geolocation_dataset.csv')
geolocation.columns

Index(['geolocation_zip_code_prefix', 'geolocation_lat', 'geolocation_lng',
       'geolocation_city', 'geolocation_state'],
      dtype='object')

In [ ]:
geolocation.shape

(1000163, 5)

In [ ]:
geolocation.duplicated().sum()

np.int64(261831)

In [ ]:
geolocation['geolocation_zip_code_prefix'].nunique()

19015

In [ ]:
geolocation = geolocation.drop_duplicates(subset='geolocation_zip_code_prefix')
geolocation.shape

(19015, 5)

In [ ]:
geolocation.to_csv('geolocation.csv', index=False)